# Generated by Django 4.2.18 on 2025-01-19 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_topic_room_host_message_room_topic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='nody',
            new_name='body',
        ),
    ]
